FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
COPY streamlit_app ./streamlit_app
CMD ["streamlit", "run", "streamlit_app/ui.py", "--server.port=8501", "--server.address=0.0.0.0"]
